name: Deploy MkDocs to GitHub Pages

on:
  workflow_run:
    workflows: ["Organize Blog Posts by Date"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 🔥 전체 커밋 히스토리를 가져와야 최신 상태 반영

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-blog-plugin 

      - name: Pull latest gh-pages
        run: git fetch origin gh-pages:gh-pages || true

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --clean --force --remote-branch gh-pages
