name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-blog-plugin

      - name: Pull latest gh-pages
        run: git fetch origin gh-pages:gh-pages || true

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --clean --force --remote-branch gh-pages
